### ISSUE TITLE
Error while configuring

### ISSUE THREAD

**Issue by aabbas90** [davzha/MESH#1]
Hi,

Thanks for making the code available. I am running into issues related to parameter configuration from hydra while running:

`python run_object_discovery.py data=clevrtex64 model=image model.slot_attention=mesh
`

with error:

`omegaconf.errors.InterpolationResolutionError: ConfigTypeError raised while resolving interpolation: Error trying to access model.slot_attention.d_slot: node model.slot_attention is not a container and thus cannot contain d_slot`

The version of hydra is 1.3.2, perhaps I am using too new version of hydra? 

Thanks,
Ahmed

**Comment by davzha** [comment]
Thanks Ahmed for bringing this to our attention! There was a mistake in the command. It should be `model/slot_attention`. Readme is updated with the fix now.
